import os

modelid='default'

print('<!DOCTYPE html>')
print('<html>')
print('<head>')
print('<meta http-equiv="Content-Type" content="text/html" charset="utf-8">')
print('<title>title</title>')
print('</head>')
print('<body>')
print('<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>')
print('<script>')
fn='../data/trainaug_id.txt'
f = open(fn,'r')
image_ids = f.read().splitlines()
f.close()
print('$(function(){')
print('var arr=[')
for i in range(len(image_ids)):
    print('"{}",'.format(image_ids[i]))
print('];')
print('var num=0;')
print('var epoch=0;')
shown=5
btn_num=[-1,"+"+"1"]
btn_if=['if (num>=0){','if (num>=0){']
for b in range(2):
    print('$(\'.btn{}\').on(\'click\', function()'.format(b)+"{")
    print(btn_if[b])
    print('num = num{};'.format(btn_num[b]))
    print('}')
    for i in range(shown):
        print('var n = num+{};'.format(i))
        print('$(".image{}").children("img").attr("src", "../logs/dssdd_{}/imgs/i_dssdd_{}_"+epoch+"_"+n+".jpg");'.format(i,modelid, modelid))
        print('$(".R{}").children("img").attr("src", "../logs/dssdd_{}/imgs/D2_dssdd_{}_"+epoch+"_"+n+".png");'.format(i,modelid, modelid))
        print('$(".S{}").children("img").attr("src", "../logs/dssdd_{}/imgs/K2_dssdd_{}_"+epoch+"_"+n+".png");'.format(i,modelid, modelid))
        print('$(".K1{}").children("img").attr("src", "../logs/dssdd_{}/imgs/K1_dssdd_{}_"+epoch+"_"+n+".png");'.format(i,modelid, modelid))
        print('$(".dk1{}").children("img").attr("src", "../logs/dssdd_{}/imgs/dk1_dssdd_{}_"+epoch+"_"+n+".png");'.format(i,modelid, modelid))
        print('$(".da1{}").children("img").attr("src", "../logs/dssdd_{}/imgs/da1_dssdd_{}_"+epoch+"_"+n+".png");'.format(i,modelid, modelid))
        print('$(".A1{}").children("img").attr("src", "../logs/dssdd_{}/imgs/A1_dssdd_{}_"+epoch+"_"+n+".png");'.format(i,modelid, modelid))
        print('$(".D1{}").children("img").attr("src", "../logs/dssdd_{}/imgs/D1_dssdd_{}_"+epoch+"_"+n+".png");'.format(i,modelid, modelid))
        print('$(".K2{}").children("img").attr("src", "../logs/dssdd_{}/imgs/K2_dssdd_{}_"+epoch+"_"+n+".png");'.format(i,modelid, modelid))
        print('$(".dk2{}").children("img").attr("src", "../logs/dssdd_{}/imgs/dk2_dssdd_{}_"+epoch+"_"+n+".png");'.format(i,modelid, modelid))
        print('$(".da2{}").children("img").attr("src", "../logs/dssdd_{}/imgs/da2_dssdd_{}_"+epoch+"_"+n+".png");'.format(i,modelid, modelid))
        print('$(".A2{}").children("img").attr("src", "../logs/dssdd_{}/imgs/D1_dssdd_{}_"+epoch+"_"+n+".png");'.format(i,modelid, modelid))
        print('$(".D2{}").children("img").attr("src", "../logs/dssdd_{}/imgs/D2_dssdd_{}_"+epoch+"_"+n+".png");'.format(i,modelid, modelid))
    print('$(\'.count_txt\').text("count "+num);')
    print('});')
btn_if=['if (epoch>=0){','if (epoch>=0){']
for b in range(2):
    print('$(\'.ebtn{}\').on(\'click\', function()'.format(b)+"{")
    print(btn_if[b])
    print('epoch = epoch{};'.format(btn_num[b]))
    print('}')
    for i in range(shown):
        print('var n = num+{}'.format(i))
        print('$(".image{}").children("img").attr("src", "../logs/dssdd_{}/imgs/i_dssdd_{}_"+epoch+"_"+n+".jpg");'.format(i,modelid, modelid))
        print('$(".R{}").children("img").attr("src", "../logs/dssdd_{}/imgs/D2_dssdd_{}_"+epoch+"_"+n+".png");'.format(i,modelid, modelid))
        print('$(".S{}").children("img").attr("src", "../logs/dssdd_{}/imgs/K2_dssdd_{}_"+epoch+"_"+n+".png");'.format(i,modelid, modelid))
        print('$(".K1{}").children("img").attr("src", "../logs/dssdd_{}/imgs/K1_dssdd_{}_"+epoch+"_"+n+".png");'.format(i,modelid, modelid))
        print('$(".dk1{}").children("img").attr("src", "../logs/dssdd_{}/imgs/dk1_dssdd_{}_"+epoch+"_"+n+".png");'.format(i,modelid, modelid))
        print('$(".da1{}").children("img").attr("src", "../logs/dssdd_{}/imgs/da1_dssdd_{}_"+epoch+"_"+n+".png");'.format(i,modelid, modelid))
        print('$(".A1{}").children("img").attr("src", "../logs/dssdd_{}/imgs/A1_dssdd_{}_"+epoch+"_"+n+".png");'.format(i,modelid, modelid))
        print('$(".D1{}").children("img").attr("src", "../logs/dssdd_{}/imgs/D1_dssdd_{}_"+epoch+"_"+n+".png");'.format(i,modelid, modelid))
        print('$(".K2{}").children("img").attr("src", "../logs/dssdd_{}/imgs/K2_dssdd_{}_"+epoch+"_"+n+".png");'.format(i,modelid, modelid))
        print('$(".dk2{}").children("img").attr("src", "../logs/dssdd_{}/imgs/dk2_dssdd_{}_"+epoch+"_"+n+".png");'.format(i,modelid, modelid))
        print('$(".da2{}").children("img").attr("src", "../logs/dssdd_{}/imgs/da2_dssdd_{}_"+epoch+"_"+n+".png");'.format(i,modelid, modelid))
        print('$(".A2{}").children("img").attr("src", "../logs/dssdd_{}/imgs/D1_dssdd_{}_"+epoch+"_"+n+".png");'.format(i,modelid, modelid))
        print('$(".D2{}").children("img").attr("src", "../logs/dssdd_{}/imgs/D2_dssdd_{}_"+epoch+"_"+n+".png");'.format(i,modelid, modelid))
    print('$(\'.epoch_txt\').text("epoch "+epoch);')
    print('});')
print('})')
print('</script>')
print('epoch')
btn_txt=['<','>']
for i in range(2):
    print('<div class="ebtn{}" style="display: inline">'.format(i))
    print('<button >'+btn_txt[i]+'</button>')
    print('</div>')
print('<br><br>')
print('count')
btn_txt=['<','>']
for i in range(2):
    print('<div class="btn{}" style="display: inline">'.format(i))
    print('<button >'+btn_txt[i]+'</button>')
    print('</div>')
print('<br><br>')
print('<p class="epoch_txt">epoch 0</p>')
print('<p class="count_txt">count 0</p>')
print('<table align="center" style="font-size : 11pt;" border="0" cellspacing="0" >')
w=200
h=200
e=0
print('<tr align=center><td>image</td><td>seed mask(sssdd)</td><td>integrated mask(second step)</td></tr>')
for i in range(shown):
    print('<tr>')
    print('<td>')
    print('<div class="image{}">'.format(i))
    print('<img src="../logs/dssdd_{}/imgs/i_dssdd_{}_{}_{}.jpg" width="{}" height="{}">'.format(modelid, modelid, e,i, w,h))
    print('</div>')
    print('</td>')
    print('<td>')
    print('<div class="S{}">'.format(i))
    print('<img src="../logs/dssdd_{}/imgs/K2_dssdd_{}_{}_{}.png" width="{}" height="{}">'.format(modelid, modelid, e,i, w,h))
    print('</div>')
    print('</td>')
    print('<td>')
    print('<div class="R{}">'.format(i))
    print('<img src="../logs/dssdd_{}/imgs/D2_dssdd_{}_{}_{}.png" width="{}" height="{}">'.format(modelid, modelid, e,i, w,h))
    print('</div>')
    print('</td>')
    print('</tr>')
    print('<tr>')
    print('<tr align=center><td>first step</td></tr>')
    print('<tr align=center><td>K1</td><td>d_k</td><td>d_a</td><td>A1</td><td></td><td>integrated_mask1</td></tr>')
    print('</tr>')
    print('<tr>')
    print('<td>')
    print('<div class="K1{}">'.format(i))
    print('<img src="../logs/dssdd_{}/imgs/K1_dssdd_{}_{}_{}.png" width="{}" height="{}">'.format(modelid, modelid, e,i, w,h))
    print('</div>')
    print('</td>')
    print('<td>')
    print('<div class="dk1{}">'.format(i))
    print('<img src="../logs/dssdd_{}/imgs/dk1_dssdd_{}_{}_{}.png" width="{}" height="{}">'.format(modelid, modelid, e,i, w,h))
    print('</div>')
    print('</td>')
    print('<td>')
    print('<div class="da1{}">'.format(i))
    print('<img src="../logs/dssdd_{}/imgs/da1_dssdd_{}_{}_{}.png" width="{}" height="{}">'.format(modelid, modelid, e,i, w,h))
    print('</div>')
    print('</td>')
    print('<td>')
    print('<div class="A1{}">'.format(i))
    print('<img src="../logs/dssdd_{}/imgs/A1_dssdd_{}_{}_{}.png" width="{}" height="{}">'.format(modelid, modelid, e,i, w,h))
    print('</div>')
    print('</td>')
    print('<td>&nbsp;&nbsp;')
    print('</td>')
    print('<td>')
    print('<div class="D1{}">'.format(i))
    print('<img src="../logs/dssdd_{}/imgs/D1_dssdd_{}_{}_{}.png" width="{}" height="{}">'.format(modelid, modelid, e,i, w,h))
    print('</div>')
    print('</td>')
    print('</tr>')
    print('<tr align=center><td>second step</td></tr>')
    print('<tr align=center><td>K2</td><td>d_k</td><td>d_a</td><td>A2</td><td></td><td>integrated_mask2</td></tr>')
    print('<tr>')
    print('<td>')
    print('<div class="K2{}">'.format(i))
    print('<img src="../logs/dssdd_{}/imgs/K2_dssdd_{}_{}_{}.png" width="{}" height="{}">'.format(modelid, modelid, e,i, w,h))
    print('</div>')
    print('</td>')
    print('<td>')
    print('<div class="dk2{}">'.format(i))
    print('<img src="../logs/dssdd_{}/imgs/dk2_dssdd_{}_{}_{}.png" width="{}" height="{}">'.format(modelid, modelid, e,i, w,h))
    print('</div>')
    print('</td>')
    print('<td>')
    print('<div class="da2{}">'.format(i))
    print('<img src="../logs/dssdd_{}/imgs/da2_dssdd_{}_{}_{}.png" width="{}" height="{}">'.format(modelid, modelid, e,i, w,h))
    print('</div>')
    print('</td>')
    print('<td>')
    print('<div class="A2{}">'.format(i))
    print('<img src="../logs/dssdd_{}/imgs/D1_dssdd_{}_{}_{}.png" width="{}" height="{}">'.format(modelid, modelid, e,i, w,h))
    print('</div>')
    print('</td>')
    print('<td>')
    print('</td>')
    print('<td>')
    print('<div class="D2{}">'.format(i))
    print('<img src="../logs/dssdd_{}/imgs/D2_dssdd_{}_{}_{}.png" width="{}" height="{}">'.format(modelid, modelid, e,i, w,h))
    print('</div>')
    print('</td>')
    print('</tr>')

print('</body></html>')
